export const productArray = [
  {
    id: 1,
    name: "Black tea",
    producer: "Producer A",
    imageUrl: "./images/black-tea.webp",
    price: 5,
    description: "Short description about 'Black tea'",
    qty: 1,
  },
  {
    id: 2,
    name: "White tea",
    producer: "Producer A",
    imageUrl: "./images/white-tea.webp",
    price: 15,
    description: "Short description about 'White tea'",
     qty: 1,
  },
  {
    id: 3,
    name: "Green tea",
     producer: "Producer B",
    imageUrl: "./images/green-tea.webp",
    price: 15,
    description: "Short description about 'Green tea'",
    qty: 1,
  },
  {
    id: 4,
    name: "Da hung Pao",
    producer: "Producer B",
    imageUrl: "./images/oolong-da-hong-pao-tea.webp",
    price: 18,
    description: "Short description about 'Da hung Pao'",
     qty: 1,
  },
  {
    id: 5,
    name: "Mint tea",
     producer: "Producer B",
    imageUrl: "./images/mint-tea.webp",
    price: 8,
    description: "Short description about 'Mint tea'",
    qty: 1,
  },
  {
    id: 6,
    name: "Black tea with apple",
     producer: "Producer C",
    imageUrl: "./images/black-tea-with-apple.webp",
    price: 17,
    description: "Short description about 'Black tea with apple'",
    qty: 1,
  },
  {
    id: 7,
    name: "Black tea with pineapple",
    producer: "Producer C",
    imageUrl: "./images/black-tea-with-pineapple.webp",
    price: 13,
    description: "Short description about 'Black tea with pineapple'",
    qty: 1,
  },
  {
    id: 8,
    name: "Black tea with pear",
    producer: "Producer D",
    imageUrl: "./images/black-tea-with-pear.webp",
    price: 14,
    description: "Short description about 'Black tea with pear'",
     qty: 1,
  },
  {
    id: 9,
    name: "Black tea with strawberries",
     producer: "Producer D",
    imageUrl: "./images/black-tea-with-strawberries.webp",
    price: 15,
    description: "Short description about 'Black tea with strawberries'",
     qty: 1,
  },
];